name: Daily DESCO Check

on:
  schedule:
    - cron: "5 2 * * *"    # 02:05 UTC = 08:05 Dhaka (avoid top of hour)
  workflow_dispatch:        # allow manual run from Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    concurrency:
      group: desco-daily
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ACCOUNT_NO: ${{ secrets.ACCOUNT_NO }}   # e.g., 500
        run: python check_balance.py
